### ISSUE TITLE
åäö - latin characters broken in interactive

### ISSUE THREAD

**Issue by haf** [fsharp/fsharp#594]
Please provide a succinct description of the issue.
#### Repro steps

Provide the steps required to reproduce the problem

TERM_PROGRAM_VERSION=3.0.4
TERM_PROGRAM=iTerm.app

```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_CTYPE=UTF-8
```
1. Start `fsharpi` on OS X
2. Type `ä` with a Swedish keyboard.
3. 
   <img width="138" alt="screen shot 2016-07-27 at 13 38 48" src="https://cloud.githubusercontent.com/assets/193115/17174147/a3073116-53ff-11e6-8f72-6ae70a8ad307.png">
#### Expected behavior

`ä` is displayed.
#### Actual behavior

`�` is displayed.
#### Known workarounds

No known.
#### Related information

Provide any related information 
- Operating system: OS X
- Branch:

```
➜  ~ fsharpi --version


error FS0243: Unrecognized option: '--version'
```
- .NET Runtime, CoreCLR or Mono Version

```
➜  ~ mono --version
Mono JIT compiler version 4.4.1 (mono-4.4.0-branch-c7sr0/4747417 Mon Jun 20 15:43:48 EDT 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
    TLS:           normal
    SIGSEGV:       altstack
    Notification:  kqueue
    Architecture:  x86
    Disabled:      none
    Misc:          softdebug
    LLVM:          yes(3.6.0svn-mono-master/a173357)
    GC:            sgen
```
- Editing Tools (e.g. Visual Studio Version): none
- Links to F# RFCs or entries on http://fslang.uservoice.com: none
- Links to performance testing scripts: none
- Indications of severity: medium

**Comment by dsyme** [comment]
@haf  It would be good to get a better understanding of where the problem might be here  - console processing can be a bit of a mystery.  I assume this is not a regression?

**Comment by haf** [comment]
No, it's been like this forever but I finally got around to reporting it. Works fine in Xamarin Studio though.

**Comment by rmunn** [comment]
This appears to be the same bug as #654. See that issue report for more details, but basically, it is caused by [the `readKeyFixup` function](https://github.com/fsharp/fsharp/blob/de709b30d9b5fdb620ff4e1d439122cdac11ffa1/src/fsharp/fsi/console.fs#L24-L42). This function is working around a bug on older versions of .Net on Windows, but in the process it's *creating* bugs on any systems that use UTF-8 console encodings (basically, pretty much every single version of Linux and OS X). Any Unicode character below U+00FF will be mangled by `readKeyFixup` as it currently stands.

One solution would be for the OS X version of `fsi.exe` to be compiled with the NO_SERVERCODEPAGES flag. Another solution would be to rewrite `readKeyFixup` so that it will be skipped if the console input encoding is UTF-8 (since the Windows versions affected by the bug that `readKeyFixup` tries to fix are never going to have a UTF-8 input encoding). Either one should solve this bug.

**Comment by haf** [comment]
This is not a discussion, this is a really bad bug in the FSI.

**Comment by dsyme** [comment]
@haf Could you check this is fixed by 4.1.5 please? thanks

**Comment by dsyme** [comment]
We believe this has been fixed, please verify if you get the chance

**Comment by haf** [comment]
Not fixed for normal developers yet.
<img width="667" alt="screen shot 2017-04-14 at 15 52 41" src="https://cloud.githubusercontent.com/assets/193115/25045053/6f942282-212a-11e7-8735-af8e0265794e.png">

**Comment by rmunn** [comment]
@haf - I just looked at the Homebrew source, and [their mono bundle](https://github.com/Homebrew/homebrew-core/blob/17faa222be03844589326dc3f54d60103f4b1e31/Formula/mono.rb) is pulling F# tag `4.1.0.2`:

```ruby
  resource "fsharp" do
    url "https://github.com/fsharp/fsharp.git",
        :tag => "4.1.0.2",
        :revision => "6ce41a922dd9ebb9766ca4b89b7a32f6a82e43e9"
  end
```

So the fix for your issue is to [tell Homebrew they need to update their Mono recipe](https://github.com/Homebrew/homebrew-core/issues).

**Comment by dsyme** [comment]
@rmunn @haf Thanks, please submit the PR to homebrew?

**Comment by rmunn** [comment]
I don't own a Mac so I wouldn't be able to test the PR, so I should probably leave this one to @haf.

**Comment by rmunn** [comment]
Actually, there's already a PR on Homebrew that would pull in the latest version of F#: https://github.com/Homebrew/homebrew-core/pull/12364

It's currently failing with the following build error:

```plain
[sierra] make[1]: *** No rule to make target `/private/tmp/mono--fsharp-20170413-38597-1uk2wo1/packages/FSharp.Compiler.Tools.4.1.5/tools/FSharp.Core.dll', needed by `build-proto'.  Stop.
```

(Full log available [here](https://bot.brew.sh/job/Homebrew/job/homebrew-core/job/PR-12364/3/console))

I won't be able to fix this one since as I mentioned I don't own a Mac, and so I'll have to leave this one to @haf (or anyone else reading this who develops on OS X). But figuring out why that build failed, and fixing it, is probably the best bet for getting this issue's fix deployed so that @haf can use it.

**Comment by neutric** [comment]
I was the one who opened that PR to upgrade to the latest version of F# (and Mono), however it currently fails as mentioned one comment above. I am not familiar with either F# or Mono, though. The `osx` build job on https://travis-ci.org/fsharp/fsharp/branches unfortunately fails for 4.1.10+ due to download problems, and older versions weren't tested against mono 4.8.1, so I have no idea whether the problem is with Homebrew or with F#. Since it was late when I submitted the PR, I then stopped bothering and decided to wait and see.

Mono 4.8.1.0 compiled just fine with F# 4.1.0.2 btw.

**Comment by dsyme** [comment]
@neutric Hmm... I looked at the homebrew PR but couldn't see the build log where the error was occurring.  Could you send a link?

BTW this osx master build passed on travis: https://travis-ci.org/fsharp/fsharp/jobs/221551455 if that helps

**Comment by haf** [comment]
@dsyme I would prefer not to be asked to support the F# compiler, its compilation or its distribution. I'm in programming for the fun of it; the creativity, the unexplored vistas, the ability to make a change in the world. My contract with a compiler and its surrounding tooling is that it should just work and if it doesn't work often enough for me, I'm going to switch language. For example, you can't expect me to test bugfixes when you haven't made testing instructions public and you don't respond to my question when asked.

My stance is that this bug hasn't been fixed, because it hasn't been published to the users of the compiler.

I think the F# team should fix their release and compile-the-compiler issues, **or I can set up deal with some people I use for outsourcing; if I can invoice 40 000 SEK/month – then we can get these problems out of the world. It's obvious that you Don is spread too thin. Myself; I'm trying to get a startup off the ground as the CEO, so I really don't have time with this stuff.

**Comment by nosami** [comment]
fwiw, this is working in Mono 5.0.0.53 (which is still unreleased and contains F# 4.1.5)

```
03:07 $ fsharpi

F# Interactive for F# 4.1
Freely distributed under the Apache 2.0 Open Source License

For help type #help;;

> "illamände";;
val it : string = "illamände"

>
```

For anyone wanting fsharp 4.1.5 now, the following should work

```bash
git co 4.1.5
./autogen.sh --prefix=/Library/Frameworks/Mono.framework/Versions/4.8.0 #or 5.0.0 etc
make
sudo make install
```

**Comment by dsyme** [comment]
@nosami Thanks for confirming the fix

@haf That's fine - we should have tested the fix - thanks for reporting it.  I was confident of the fix after looking at it. But localization issues are tricky (different OS, locale, keyboards etc.) and it's reassuring to see them validated on end-user machines if possible.

**Comment by dsyme** [comment]
@haf You've historically owned the [fsharp docker image repo](https://github.com/fsprojects/docker-fsharp).  Do you want to transfer ownership of that?  

I've been [documenting the list of tagged packagings of F#](https://github.com/fsharp/fsharp/blob/master/README.md).  With good documentation we can probably update these delivery channels more consistently.

**Comment by neutric** [comment]
@dsyme Build log as [gist](https://gist.githubusercontent.com/neutric/6b3792dbc59885cf5b8f66e53d50b5ad/raw/b54a18c3da92a5cf27f2d50a64792bf8e4d87660/build.log).

**Comment by dsyme** [comment]
@neutric I think some sort of parallel build/make must be enabled for that build that isn't enabled by our travis macOS build.  The build exposes an inaccurate dependency declaration in the makefiles

In any case I've submitted a tentative fix here https://github.com/fsharp/fsharp/pull/724.  It's possible similar problems will be revealed at the next step.  What's the process for progressively testing new iterations?  Do we just integrate the possible fix into this repo, then update the brew PR etc.?    Or can we point the brew PR to https://github.com/fsharp/fsharp/pull/724?

Thanks!

**Comment by dsyme** [comment]
@neutric I'll start a new issue about this

**Comment by dsyme** [comment]
See https://github.com/fsharp/fsharp/issues/725

**Comment by neutric** [comment]
@dsyme We indeed do parallel builds by default, can disable that selectively though if needed. I can point the "formula" to a specific commit for testing, it doesn't have to be committed to master. I'll do so with the patch from #724 once I see all is good in your CI.

**Comment by neutric** [comment]
@haf Mono via Homebrew now ships F# 4.1.13, so your issue should be resolved.
