### ISSUE TITLE
Dependency problem with an RPM package

### ISSUE THREAD

**Issue by LaurentTreguier** [fsharp/fsharp#699]
Hello there, not so long ago I started making a specfile to build fsharp RPM packages for Fedora on [Copr](https://copr.fedorainfracloud.org/coprs/tcg/devel/packages/). Up until recently it seemed to work well, however starting with version 4.1.5 there is a weird problem with dependencies.
As you may or may not know, RPM can automatically detect package dependencies, as well as what a package provides.
For instance this is what `fsharp-4.1.4` provides:
```
fsharp = 4.1.4-1.fc25
mono(FSharp.Build) = 4.4.1.0
mono(FSharp.Compiler) = 4.4.1.0
mono(FSharp.Compiler.Interactive.Settings) = 4.4.1.0
mono(FSharp.Compiler.Server.Shared) = 4.4.1.0
mono(FSharp.Core) = 4.3.0.0
mono(FSharp.Core) = 4.3.1.0
mono(FSharp.Core) = 4.4.0.0
mono(FSharp.Core) = 4.4.1.0
mono(System.Collections.Immutable) = 1.2.0.0
mono(System.Reflection.Metadata) = 1.4.1.0
mono(fsc) = 4.4.1.0
mono(fsi) = 4.4.1.0
mono(fsiAnyCpu) = 4.4.1.0
mono(policy.2.0.FSharp.Core) = 0.0.0.0
mono(policy.2.3.FSharp.Core) = 0.0.0.0
mono(policy.3.259.FSharp.Core) = 0.0.0.0
mono(policy.3.3.FSharp.Core) = 0.0.0.0
mono(policy.3.47.FSharp.Core) = 0.0.0.0
mono(policy.3.7.FSharp.Core) = 0.0.0.0
mono(policy.3.78.FSharp.Core) = 0.0.0.0
mono(policy.4.0.FSharp.Core) = 0.0.0.0
mono(policy.4.3.FSharp.Core) = 0.0.0.0
mono(policy.4.4.FSharp.Core) = 0.0.0.0
```

And this is what it requires:
```
/bin/sh
/usr/bin/gdb
/usr/bin/valgrind
mono(FSharp.Compiler) = 4.4.1.0
mono(FSharp.Compiler.Server.Shared) = 4.4.1.0
mono(FSharp.Core) = 4.4.1.0
mono(Microsoft.Build) = 12.0.0.0
mono(Microsoft.Build.Framework) = 12.0.0.0
mono(Microsoft.Build.Tasks.v12.0) = 12.0.0.0
mono(Microsoft.Build.Utilities.v12.0) = 12.0.0.0
mono(System) = 4.0.0.0
mono(System.Collections) = 4.0.0.0
mono(System.Collections.Immutable) = 1.2.0.0
mono(System.Core) = 4.0.0.0
mono(System.Diagnostics.Debug) = 4.0.0.0
mono(System.Globalization) = 4.0.0.0
mono(System.IO) = 4.0.0.0
mono(System.Linq) = 4.0.0.0
mono(System.Numerics) = 4.0.0.0
mono(System.Reflection) = 4.0.0.0
mono(System.Reflection.Extensions) = 4.0.0.0
mono(System.Reflection.Metadata) = 1.4.1.0
mono(System.Reflection.Primitives) = 4.0.0.0
mono(System.Resources.ResourceManager) = 4.0.0.0
mono(System.Runtime) = 4.0.0.0
mono(System.Runtime.Extensions) = 4.0.0.0
mono(System.Runtime.InteropServices) = 4.0.0.0
mono(System.Runtime.Remoting) = 4.0.0.0
mono(System.Text.Encoding) = 4.0.0.0
mono(System.Text.Encoding.Extensions) = 4.0.0.0
mono(System.Threading) = 4.0.0.0
mono(System.Windows.Forms) = 4.0.0.0
mono(mscorlib) = 4.0.0.0
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
```

Some of the dependencies are satisfied by the package itself, such as `mono(FSharp.Core) = 4.4.1.0` or `mono(System.Collections.Immutable) = 1.2.0.0`.

With fsharp 4.1.5 and 4.1.6, `mono(System.Collections.Immutable)` is required twice, at version `1.2.0.0` and at version `1.2.1.0`, both at the same time. But the package doesn't provide `mono(System.Collections.Immutable) ` version `1.2.0.0` anymore, only the newer `1.2.1.0` version. So now the package cannot be installed because it doesn't provide something that it provided itself before.

This problem may not be directly related to the fsharp code itself, but I wanted to know if anyone had a clue about what's going on here. Though I made a specfile for fsharp, I still don't know much about it yet.

Here is the specfile used:
```specfile
Name:           fsharp
Version:        4.1.6
Release:        1%{?dist}
Summary:        The Open Edition of the F# compiler, core library and tools

License:        Apache-2.0
URL:            http://fsharp.org/
Source0:        https://github.com/%{name}/%{name}/archive/%{version}.tar.gz#/%{name}-%{version}.tar.gz

BuildArch:      noarch
BuildRequires:  %{_bindir}/autoreconf
BuildRequires:  %{_bindir}/automake
BuildRequires:  %{_bindir}/nuget
BuildRequires:  mono-devel >= 4.4.0
BuildRequires:  mono-wcf   >= 4.4.0
Requires:       %{_bindir}/gdb
Requires:       %{_bindir}/valgrind
# Without this, the package is not installable anymore
Provides:       mono(System.Collections.Immutable) = 1.2.0.0

%description
F# is a mature, open source, cross-platform, functional-first programming language.
It empowers users and organizations to tackle complex computing problems with simple, maintainable and robust code.


%prep
%autosetup
cert-sync --user /etc/pki/tls/certs/ca-bundle.crt


%build
autoreconf
%configure --libexecdir=%{_monodir}/.. --libdir=%{_monodir}/..
make


%install
rm -rf $RPM_BUILD_ROOT
%make_install


%files
%defattr(-,root,root)
%{_bindir}/fsharp*
%{_monodir}/fsharp
%{_monogacdir}/FSharp.*
%{_monogacdir}/*.FSharp.Core
"%{_monodir}/Microsoft F#"
"%{_monodir}/Microsoft SDKs/F#"
%{_monodir}/xbuild/Microsoft/VisualStudio/*/FSharp
```

#### Repro steps
- Build the package using the specfile
- Try to install the built package

#### Expected behavior
The package should be installed.

#### Actual behavior
The package depends on `mono(System.Collections.Immutable) = 1.2.0.0` but doesn't provide it anymore, unlike the previous versions. It now only provides version `1.2.1.0` but requires both verison `1.2.0.0` and version `1.2.1.0`.

#### Known workarounds
For now, manually telling in the specfile that fsharp provides `mono(System.Collections.Immutable) = 1.2.0.0` make the package installable, but I don't know if everything is working as intended.

#### Related information
* Operating system: Fedora 25 x86_64
* Mono is version 4.4.2

Any kind of ideas or suggestions would be much appreciated. Also, sorry for the long wall of copied-and-pasted stuff.

**Comment by dsyme** [comment]
@LaurentTreguier It looks like the RPM packages are actually looking at .NET DLL dependencies, not NuGet package dependencies

I'm trying to work out where the danglnig dependency on ``System.Collections.Immutable`` 1.2.0.0 is coming from.  Maybe we need to add a binding redirect for this case, or auto-generate them.

**Comment by dsyme** [comment]
@LaurentTreguier OK, the problem is that System.Reflection.Metadata has a reference to that.  We need a binding redirect - I'm hopeful that the RPM packaging machinery will then do the right thing (this is my first experience of it)

**Comment by LaurentTreguier** [comment]
Thanks for the very fast response! 
I have no idea how the package could be added to fsharp.org however.

**Comment by dsyme** [comment]
@LaurentTreguier Fix is in 4.1.7. Please post back an update about whether this fixes the issue? Thanks

**Comment by dsyme** [comment]
I _think_ this is fixed, so will close it, but please reopen if not

**Comment by LaurentTreguier** [comment]
@dsyme Unfortunately it looks like the problem is still there in 4.1.7... Also, I can't reopen the issue. Is it because you, as a contributor, closed it ?

**Comment by dsyme** [comment]
@LaurentTreguier Well, I think the issue is harmless, in the sense that F# will continue to work.  But I suspect this is a bug in the tool that is computing the dependencies - as far as I can tell nothing in the F# package now requires that version of the DLL

It's odd because I would have thought such a tool would know about binding redirects, they are very common in .NET/Mono

**Comment by dsyme** [comment]
> For now, manually telling in the specfile that fsharp provides mono(System.Collections.Immutable) = 1.2.0.0 make the package installable, but I don't know if everything is working as intended.


check
- Does ``fsharpi`` run?
` Does ``fsharpc`` run on a small test input file, e.g. one containing ``printfn "hello %d" 42``, and then does the output exe run?

**Comment by LaurentTreguier** [comment]
@dsyme both `fsharpi` and `fsharpc` run correctly. I'll try to figure out how RPM gets its automatic dependencies and see if that' where the problem comes from.
For now I guess I'll just roll RPMs using `Provides: mono(System.Collections.Immutable) = 1.2.0.0`

**Comment by LaurentTreguier** [comment]
@dsyme apparently the RPM module that detects dependencies for all things mono related uses `monodis --assemblyref`. I tried using it on every compiled assembly and found out that after compiling fsharp, `Release/net40/bin/System.Reflection.Metadata.dll` depends on `System.Collections.Immutable` at version 1.2.0.0.

**Comment by dsyme** [comment]
@LaurentTreguier Yes, that technique is incorrect.  A .NET component will commonly depend on a prior version of dependency, but have that resolved courtesy of a config file at startup, like [this one](https://github.com/fsharp/fsharp/blob/master/src/fsharp/Fsc/fsc.exe.config).   

This will become more and more common since the amount of componentization in .NET is rapidly increasing.

**Comment by enricosada** [comment]
I probably fixed it with https://github.com/fsharp/fsharp/pull/732

Now the nupkg bundle `System.Collections.Immutable` 1.2.0.0 and all `tools` assemblies reference 1.2.0.0.
The binding redirect was pointing to 1.2.1.0, but i remove that with the referenced PR

**Comment by LaurentTreguier** [comment]
@enricosada this indeed seems to fix the issue; at least when building the package from mater it's gone 🎉

**Comment by enricosada** [comment]
good.

i am trying to upload package `4.1.15` to nuget, i'll close when done

**Comment by enricosada** [comment]
Ok done with https://www.nuget.org/packages/FSharp.Compiler.Tools/4.1.15.
